#
# Find the QGLViewer includes and libraries
#

FIND_PATH(QGLVIEWER_INCLUDE_DIR NAMES QGLViewer/qglviewer.h)
FIND_LIBRARY(QGLVIEWER_LIBRARY NAMES qglviewer-qt4 QGLViewer QGLViewer2)

IF(QGLVIEWER_INCLUDE_DIR AND QGLVIEWER_LIBRARY)
  SET(QGLVIEWER_FOUND "YES")
ENDIF()

MARK_AS_ADVANCED( QGLVIEWER_INCLUDE_DIR QGLVIEWER_LIBRARY )
